---
- name: Install essential packages
  become: true
  pacman:
    name:
      - base-devel
      - git
      - xorg
      - xorg-xinit
      - xorg-server
      - mesa
      - vulkan-radeon
      - libva-mesa-driver
      - linux-firmware
      - ttf-dejavu
      - ttf-liberation
    state: present

- name: Create source directory
  file:
    path: "{{ ansible_user_dir }}/.local/src"
    state: directory
    mode: "0755"

- name: Clone dwm
  git:
    repo: https://git.suckless.org/dwm
    dest: "{{ ansible_user_dir }}/.local/src/dwm"
    update: yes

- name: Clone dmenu
  git:
    repo: https://git.suckless.org/dmenu
    dest: "{{ ansible_user_dir }}/.local/src/dmenu"
    update: yes

- name: Build and install dwm
  become: true
  make:
    chdir: "{{ ansible_user_dir }}/.local/src/dwm"
    target: install

- name: Build and install dmenu
  become: true
  make:
    chdir: "{{ ansible_user_dir }}/.local/src/dmenu"
    target: install

- name: Copy .xinitrc
  copy:
    src: xinitrc
    dest: "{{ ansible_user_dir }}/.xinitrc"
    mode: "0644"
