---
- name: Install ghostty
  ansible.builtin.package:
    name: ghostty
    state: latest
  become: yes

- name: Create ghostty config directory
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/ghostty"
    state: directory
    mode: "0755"

- name: Link ghostty config
  ansible.builtin.file:
    src: "{{ role_path }}/files/config"
    dest: "{{ ansible_user_dir }}/.config/ghostty/config"
    state: link
