---
- name: Install tmux
  ansible.builtin.package:
    name: tmux
    state: latest
  become: yes

- name: Create tmux config directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/tmux"
    state: directory

- name: Symlink tmux.conf
  ansible.builtin.file:
    src: "{{ role_path }}/files/tmux.conf"
    dest: "{{ ansible_user_dir }}/.config/tmux/tmux.conf"
    state: link
    force: yes
