#!/bin/sh

# Auto run with startx

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

# Update dbus environment with all variables
dbus-update-activation-environment --systemd --all

# Start dwm (replace current process)
exec dwm
