#!/bin/sh

xrandr --output DP-1 --off --output DP-2 --mode 2560x1440 --pos 1920x0 --rotate normal --output DP-3 --mode 1920x1080 --pos 0x357 --rotate normal --output HDMI-1 --off --output HDMI-1-2 --off --output DP-1-4 --off --output DP-1-5 --off --output DP-1-6 --off
setbg &
xset s off -dpms

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!

autostart="dunst remaps xcompmgr xbanish player_loop"

for program in $autostart; do
    pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

[ -n "$xrdbpid" ] && wait "$xrdbpid"


