---
- name: Install Neovim
  ansible.builtin.package:
    name:
      - neovim
      - tree-sitter
      - ripgrep
      - fd
    state: latest
  become: yes

- name: Create Neovim config directory
  ansible.builtin.file:
    mode: "0755"
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: directory

- name: Symlink init.lua
  ansible.builtin.file:
    src: "{{ role_path }}/files/init.lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"
    state: link
    force: yes

- name: Symlink lua directory
  ansible.builtin.file:
    src: "{{ role_path }}/files/lua"
    dest: "{{ ansible_user_dir }}/.config/nvim/lua"
    state: link
    force: yes
